enum Tokens {RELOP = 256, ADDOP, MULOP, ANDOP, BEGIN_, BOOLEAN, END, ENDREDUCE,
	FUNCTION, INTEGER, IS, REDUCE, RETURNS, IDENTIFIER, INT_LITERAL, ARROW, CASE, ELSE, ENDCASE, ENDIF, IF, OTHERS, REAL, THEN, WHEN, OROP, NOTOP, REMOP, EXPOP, BOOL_LITERAL, REAL_LITERAL};
